services:
  node:
    image: node:22
    command: npm run dev -- --host
    ports:
    - 5173:5173
    environment:
      PG: postgres://postgres:dev@db:5432/
    working_dir: /opt/repo
    volumes:
    - .:/opt/repo
  db:
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
    - pg:/var/lib/postgresql/data
volumes:
  pg:
